# Use the official Python image
FROM python:3.12

# Set the working directory
WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
COPY gunicorn.conf.py .
COPY startup.sh .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire application
COPY . .

# Expose the API port
EXPOSE 8000

# Start FastAPI with Uvicorn
RUN chmod +x /wait-for-postgres.sh

# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
