name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: oxygene_user
          POSTGRES_PASSWORD: strongpassword
          POSTGRES_DB: oxygene_test
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          pytest --disable-warnings

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (Placeholder)
        run: echo "Deploying application..."
